'use strict';

const INSPECTIONS = [
  ['load','発電機負荷',15],['otherGenerator','他発電機の状態',15],['exhaustTemps','各筒排気温度',15],['fuelValve','燃料弁',90],['exhaustValve','排気弁',90],['exhaustSensor','排気温度センサー',30],['airFilter','吸気フィルター',60],['turbo','ターボチャージャー',60],['boostPressure','過給空気圧力',15],['coolingPump','冷却水ポンプ',60],['coolingStrainer','冷却水ストレーナ',60],['coolingValve','冷却水弁',60],['expansionTank','膨張タンク水位',30],['oilLevel','潤滑油量',15],['oilTemp','潤滑油温度',15],['oilPump','潤滑油ポンプ',60],['oilStrainer','潤滑油ストレーナ',60],['oilLeak','漏油',30],['pressureSensor','圧力センサー',30],['crankcase','クランクケース',60],['bearingTemp','軸受温度',15]
];
const SAFE_LABELS={report:'責任者または当直責任者へ報告する',standbyCheck:'待機発電機の使用可否を確認する',standbyStart:'待機発電機を始動する',parallel:'発電機を並列運転する',transfer:'負荷を健全な発電機へ移行する',breaker:'対象発電機の遮断器を開放する',stop:'対象発電機を停止する',fuelOff:'燃料供給を遮断する',airOff:'始動空気を遮断する',autoOff:'自動始動を無効化する',loto:'LOTOまたは作業中表示を行う',cool:'高温部が安全な温度になるまで待つ',ppe:'必要な保護具を着用する'};
const BASE_SAFE=['report','standbyCheck','standbyStart','parallel','transfer','breaker','stop','fuelOff','airOff','autoOff','loto','ppe'];

// 新規ケースは同じ形のオブジェクトをこの配列へ追加する。
const CASES=[
 {id:'cylinder-high',alarm:'NO.3 CYLINDER EXHAUST GAS TEMPERATURE HIGH',title:'単筒排気温度 HIGH',cause:'No.3シリンダー燃料弁の噴霧不良',data:[['発電機負荷','72%','normal'],['No.1 排気温度','358℃','normal'],['No.2 排気温度','364℃','normal'],['No.3 排気温度','465℃ · HIGH','danger'],['No.4 排気温度','359℃','normal'],['冷却水 出口','78℃','normal'],['潤滑油圧力','4.2 bar','normal'],['過給空気圧力','NORMAL','normal']],important:['load','exhaustTemps','fuelValve','exhaustValve','exhaustSensor'],findings:{load:'負荷は72%。過負荷ではありません。',exhaustTemps:'No.3だけが465℃で、他筒より約100℃高い状態です。',fuelValve:'No.3燃料弁のノズル先端にカーボンが付着。噴霧が不均一で、開弁圧力も基準値より低下しています。',exhaustValve:'No.3排気弁の気密と作動に異常はありません。',exhaustSensor:'基準計との比較で指示差は許容範囲内です。'},causes:['No.3シリンダー燃料弁の噴霧不良','No.3排気弁の吹き抜け','冷却水流量不足','排気温度センサー故障','発電機の過負荷'],action:'燃料弁を整備済み予備品と交換する',wrongActions:['燃料弁外部だけを拭いて再使用する','排気弁クリアランスを調整する','発電機負荷をさらに上げる','排気温度センサーを交換する'],safe:[...BASE_SAFE,'cool'],repair:'No.3燃料弁を交換しています',trial:{label:'No.3 排気温度',values:['465℃','420℃','390℃','365℃']},hints:['一つのシリンダーだけ数値が異なるのか、全筒が同じ傾向なのか比較してください。','今回の異常は燃焼状態に関係する可能性があります。','燃料弁、排気弁、温度センサーの点検結果を比較してください。'],learning:'単筒だけの排気温度偏差では、計器の信頼性を確かめながら燃焼に関わる部品を絞り込みます。'},
 {id:'overload',alarm:'ALL CYLINDERS EXHAUST GAS TEMPERATURE HIGH',title:'全筒排気温度 HIGH',cause:'発電機の過負荷',data:[['発電機負荷','96% · HIGH','danger'],['No.1 排気温度','438℃ · HIGH','danger'],['No.2 排気温度','430℃ · HIGH','danger'],['No.3 排気温度','445℃ · HIGH','danger'],['No.4 排気温度','436℃ · HIGH','danger'],['冷却水 出口','82℃ · CAUTION','warning'],['潤滑油圧力','4.1 bar','normal'],['過給空気圧力','NORMAL','normal']],important:['load','otherGenerator','exhaustTemps','airFilter','coolingPump'],findings:{load:'負荷が定格に近い96%まで上昇しています。',otherGenerator:'待機発電機は始動可能。大容量補機の始動後、負荷分担が偏っています。',exhaustTemps:'全筒が430～445℃で同じ傾向です。',airFilter:'差圧は正常で、吸気制限はありません。',coolingPump:'吐出圧力・流量は正常です。'},causes:['発電機の過負荷','全燃料弁の同時噴霧不良','冷却水ポンプ能力低下','吸気フィルター詰まり'],action:'待機発電機を始動して負荷を分担する',wrongActions:['全燃料弁を交換する','冷却水流量を下げる','負荷をさらに上げる','全排気温度センサーを交換する'],safe:['report','standbyCheck','standbyStart','parallel','transfer','ppe'],repair:'待機機へ負荷を適正に分担しています',trial:{label:'発電機負荷',values:['96%','88%','76%','62%']},hints:['全シリンダーに共通する変化へ注目してください。','まず熱の発生量と発電機負荷の関係を確認してください。','他発電機の状態と負荷分担を確認してください。'],learning:'全筒が同様に高温なら、個別部品より共通要因である負荷や吸排気・冷却を優先します。'},
 {id:'cooling',alarm:'JACKET COOLING WATER OUTLET TEMPERATURE HIGH',title:'冷却水出口温度 HIGH',cause:'冷却水ストレーナの詰まりによる流量不足',data:[['発電機負荷','68%','normal'],['排気温度','全筒ほぼ均一','normal'],['冷却水 入口','76℃','normal'],['冷却水 出口','96℃ · HIGH','danger'],['入口出口温度差','20℃ · HIGH','warning'],['潤滑油圧力','4.2 bar','normal'],['潤滑油温度','NORMAL','normal'],['運転状態','RUNNING','normal']],important:['coolingPump','coolingStrainer','coolingValve','expansionTank'],findings:{coolingPump:'ポンプ吐出圧はあるものの、系統流量が不足しています。',coolingStrainer:'前後差圧が大きく、内部に錆片と異物が堆積しています。',coolingValve:'弁は所定位置で、固着はありません。',expansionTank:'水位は正常範囲で、補給の必要はありません。'},causes:['冷却水ストレーナの詰まりによる流量不足','冷却水温度センサー故障','発電機の過負荷','潤滑油量不足'],action:'冷却水ストレーナを切り替えて清掃する',wrongActions:['冷却水流量を下げる','潤滑油ストレーナを清掃する','燃料弁を交換する','温度センサーだけを交換する'],safe:[...BASE_SAFE,'cool'],repair:'健全側へ切り替え、冷却水ストレーナを清掃しています',trial:{label:'冷却水 出口温度',values:['96℃','90℃','84℃','79℃']},hints:['入口と出口の温度差を確認してください。','冷却水の流量を妨げる要因を考えてください。','ポンプ、弁、ストレーナの点検結果を比較してください。'],learning:'温度上昇では入口・出口差と流量を確認し、ポンプ、弁、ストレーナを系統的に切り分けます。'},
 {id:'oil',alarm:'LUBRICATING OIL PRESSURE LOW',title:'潤滑油圧力 LOW',cause:'潤滑油ストレーナの詰まり',data:[['発電機負荷','65%','normal'],['潤滑油圧力','2.5 bar · LOW','danger'],['通常油圧','4.0～4.5 bar','normal'],['潤滑油温度','NORMAL','normal'],['潤滑油量','NORMAL','normal'],['軸受温度','NORMAL','normal'],['排気温度','全筒均一','normal'],['運転状態','RUNNING','warning']],important:['oilLevel','oilTemp','oilPump','oilStrainer','pressureSensor','oilLeak'],findings:{oilLevel:'サンプタンク油量は正常範囲です。',oilTemp:'油温は正常で、粘度低下を示す所見はありません。',oilPump:'異音はなく、駆動状態は正常です。',oilStrainer:'差圧が上昇し、流れが制限されています。',pressureSensor:'機械式圧力計も低値を示し、センサー単独故障ではありません。',oilLeak:'外部への明確な漏油はありません。'},causes:['潤滑油ストレーナの詰まり','潤滑油圧力センサー故障','サンプタンク油量不足','軸受損傷'],action:'潤滑油ストレーナを切り替えて清掃する',wrongActions:['潤滑油を無条件に大量補給する','圧力センサーだけを交換する','冷却水ストレーナを清掃する','低油圧のまま負荷を上げる'],safe:[...BASE_SAFE],repair:'健全側へ切り替え、潤滑油ストレーナを清掃しています',trial:{label:'潤滑油圧力',values:['2.5 bar','3.1 bar','3.8 bar','4.2 bar']},hints:['油量・油温・実圧力を順に確認してください。','圧力を作る部分と流れを妨げる部分を切り分けてください。','ストレーナ前後差圧を確認してください。'],learning:'低油圧は重大事故につながるため、油量・温度・漏れ・ポンプ・ストレーナ・計器を迅速に切り分けます。'},
 {id:'intake',alarm:'GENERATOR OUTPUT LOW / EXHAUST TEMPERATURE HIGH',title:'出力低下・排気温度上昇',cause:'吸気フィルターの詰まり',data:[['負荷指令','75%','normal'],['実出力','62% · LOW','danger'],['排気温度','通常比 +30～40℃','warning'],['過給空気圧力','LOW','danger'],['冷却水温度','NORMAL','normal'],['潤滑油圧力','NORMAL','normal'],['燃料ラック','増加傾向','warning'],['運転状態','RUNNING','normal']],important:['airFilter','boostPressure','turbo','load','exhaustTemps'],findings:{airFilter:'塵埃が堆積し、フィルター前後差圧が高くなっています。',boostPressure:'負荷に対して過給空気圧力が低く、空気量不足を示します。',turbo:'回転と外観に明確な損傷はありません。',load:'負荷指令75%に対し、実出力は62%です。',exhaustTemps:'全筒が通常より30～40℃高く、燃焼空気不足の傾向です。'},causes:['吸気フィルターの詰まり','ターボチャージャー重大損傷','燃料ラック固着','発電機の電気的過負荷'],action:'吸気フィルターを清掃または交換する',wrongActions:['燃料ラックをさらに増やす','ターボチャージャーを直ちに交換する','冷却水流量を下げる','排気温度センサーを交換する'],safe:[...BASE_SAFE,'cool'],repair:'吸気フィルターを清掃・交換しています',trial:{label:'実出力 / 過給空気圧力',values:['62% / LOW','66% / RISING','71% / NORMAL','75% / NORMAL']},hints:['出力低下と全筒温度上昇に共通する条件を考えてください。','燃焼に必要な空気量に注目してください。','過給空気圧力、フィルター差圧、ターボ本体を比較してください。'],learning:'出力低下と全筒温度上昇、低過給圧の組合せから吸気抵抗を疑い、ターボ損傷と切り分けます。'}
];

const app=document.querySelector('#app'),modal=document.querySelector('#modal'),modalContent=document.querySelector('#modal-content'),toast=document.querySelector('#toast');
let timerId=null,lastCaseId=null;
const freshState=()=>({currentCase:null,difficulty:'beginner',currentStep:0,startTime:null,elapsedTime:0,simulatedWorkTime:0,inspectedItems:new Set(),inspectionHistory:[],selectedCause:null,causeMistakes:0,completedSafetySteps:[],unsafeActionCount:0,selectedAction:null,actionMistakes:0,hintCount:0,aiAssistCount:0,score:1000,isRecovered:false,feedback:'',repairing:false,trialIndex:0});
let state=freshState();
const STEPS=['警報確認','データ確認','点検','原因判断','安全措置','修理・調整','試運転'];

function esc(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
function formatTime(sec){return `${String(Math.floor(sec/60)).padStart(2,'0')}:${String(sec%60).padStart(2,'0')}`;}
function stepper(){return `<div class="stepper">${STEPS.map((s,i)=>`<div class="step ${i===state.currentStep?'active':i<state.currentStep?'done':''}"><b>${i+1}</b> <span>${s}</span></div>`).join('')}</div>`;}
function gameHeader(){return `${stepper()}<div class="status-strip"><div class="alarm"><i class="alarm-light"></i><span>${esc(state.currentCase.alarm)}</span></div><div class="time-box">実時間 <b id="elapsed">${formatTime(state.elapsedTime)}</b></div><div class="time-box">作業時間 <b>${formatTime(state.simulatedWorkTime)}</b></div></div>`;}
function setScreen(html,inGame=false){app.innerHTML=html;document.body.classList.toggle('in-game',inGame);window.scrollTo(0,0);}
function intro(){stopTimer();state=freshState();setScreen(`<section class="hero"><div class="eyebrow">MARINE ENGINEERING TRAINING</div><h1>GENERATOR<br>TROUBLESHOOTER<span>発電機トラブル対応シミュレーター</span></h1><p class="lead">症状を読み取り、原因を特定し、安全に復旧せよ</p></section><section class="panel"><h2>このアプリで体験すること</h2><p class="lead" style="margin:0">船の電力を支える発電機に異常が発生しました。機関士の仕事は、警報を消すことだけではありません。計器の数値、他のシリンダーとの違い、機器の状態を確認し、原因を絞り込み、安全な手順で正常状態へ復旧させます。</p><p class="muted">このシミュレーターでは「症状を見る」「点検する」「原因を考える」「安全を確保する」「適切に処置する」という機関士の判断を体験します。</p></section><h2 class="section-title">ゲームの目的</h2><div class="grid cols-4">${['警報と運転データから異常の特徴をつかむ','必要な点検箇所を効率よく選ぶ','点検結果から原因を特定する','安全手順を守って正しい処置を行う'].map((x,i)=>`<article class="card"><div class="card-num">0${i+1}</div><p>${x}</p></article>`).join('')}</div><h2 class="section-title">操作の流れ</h2><div class="flow">${STEPS.map((x,i)=>`${i?'<span class="flow-arrow">›</span>':''}<div class="flow-step"><b>${i+1}</b><br>${x}</div>`).join('')}</div><h2 class="section-title">評価される内容</h2><div class="grid cols-3">${['原因を正しく特定','不要な点検を削減','適切な処置を選択','安全手順を遵守','早く復旧','ヒントなしで判断'].map(x=>`<div class="card">✓ ${x}</div>`).join('')}</div><h2 class="section-title">注意事項</h2><div class="notice">実際の船舶では、機器メーカーの取扱説明書、船内手順書、SMS、責任者の指示に従う必要があります。<br>このアプリは教育用シミュレーションであり、実機の整備手順を代替するものではありません。</div><div class="hero-actions center"><button class="btn large" data-action="setup">ミッションを開始する →</button></div>`);}
function setup(){setScreen(`<div class="mission-head"><div><div class="eyebrow">MISSION SETUP</div><h1>難易度を選択</h1><p class="muted">5種類の異常からランダムに出題されます。</p></div></div><div class="grid cols-3">${[['beginner','初級',['関連系統のヒント','一部候補を強調','詳しい誤操作説明','制限時間なし']],['intermediate','中級',['系統レベルのヒント','候補強調なし','タイムとスコアを記録']],['advanced','上級',['ヒントなし','不要点検・誤処置の減点大','運転データ中心で判断']]].map(([id,name,ls])=>`<label class="difficulty"><input type="radio" name="difficulty" value="${id}" ${id==='beginner'?'checked':''}><div class="difficulty-card"><h3>${name}</h3><ul>${ls.map(x=>`<li>${x}</li>`).join('')}</ul></div></label>`).join('')}</div><div class="screen-actions"><button class="btn ghost" data-action="title">戻る</button><button class="btn large" data-action="start">ランダムミッション開始</button></div>`);}
function start(caseId=null){const difficulty=document.querySelector('input[name=difficulty]:checked')?.value||state.difficulty||'beginner';state=freshState();state.difficulty=difficulty;let pool=CASES;if(!caseId&&lastCaseId&&CASES.length>1)pool=CASES.filter(c=>c.id!==lastCaseId);state.currentCase=caseId?CASES.find(c=>c.id===caseId):pool[Math.floor(Math.random()*pool.length)];lastCaseId=state.currentCase.id;state.startTime=Date.now();timerId=setInterval(tick,1000);monitor();}
function tick(){state.elapsedTime=Math.floor((Date.now()-state.startTime)/1000);const el=document.querySelector('#elapsed');if(el)el.textContent=formatTime(state.elapsedTime);}
function stopTimer(){if(timerId)clearInterval(timerId);timerId=null;}
function machineSvg(){return `<svg viewBox="0 0 640 390" role="img" aria-label="4気筒ディーゼル発電機模式図"><path class="pipe" stroke="#ff805d" d="M105 70H395Q430 70 430 105V130"/><path class="pipe" stroke="#55b9e9" d="M75 280H390Q430 280 430 240"/><path class="pipe" stroke="#4bd58a" d="M110 330H440"/><rect x="80" y="110" width="330" height="155" rx="18" fill="#243d4e" stroke="#507085" stroke-width="3"/>${[0,1,2,3].map((_,i)=>`<g><rect x="${105+i*72}" y="130" width="54" height="110" rx="7" fill="${i===2&&state.currentCase.id==='cylinder-high'?'#743340':'#122838'}" stroke="${i===2&&state.currentCase.id==='cylinder-high'?'#ff6977':'#598096'}"/><text x="${132+i*72}" y="192" text-anchor="middle" class="machine-label">No.${i+1}</text></g>`).join('')}<circle cx="455" cy="172" r="38" fill="#17384c" stroke="#54c7ec" stroke-width="4"/><path d="M455 145v54M428 172h54M436 153l38 38M474 153l-38 38" stroke="#54c7ec" stroke-width="5"/><text x="455" y="225" text-anchor="middle" class="machine-label">TURBO</text><rect x="510" y="105" width="105" height="160" rx="52" fill="#193247" stroke="#ffc857" stroke-width="4"/><text x="562" y="190" text-anchor="middle" class="machine-label">GENERATOR</text><text x="90" y="55" class="machine-label">排気系統</text><text x="75" y="308" class="machine-label">吸気系統</text><text x="110" y="360" class="machine-label">冷却水 / 潤滑油系統</text></svg>`;}
function monitor(){state.currentStep=0;setScreen(`${gameHeader()}<div class="monitor-layout"><section class="panel machine"><div class="eyebrow">GENERATOR No.2 · RUNNING</div><h2>ディーゼル発電機 模式図</h2>${machineSvg()}</section><section class="panel"><div class="eyebrow">LIVE OPERATING DATA</div><h2>運転データ</h2><div class="data-grid">${state.currentCase.data.map(([k,v,s])=>`<div class="gauge"><small>${k}</small><strong class="state-${s}">${v}</strong></div>`).join('')}</div></section></div><div class="screen-actions"><button class="btn" data-action="inspect">データを比較し、点検へ →</button></div>`,true);}
function inspect(){state.currentStep=2;const recommended=state.difficulty==='beginner';setScreen(`${gameHeader()}<div class="inspection-layout"><section class="panel"><div class="eyebrow">SELECT INSPECTION POINT</div><h2>どこを点検しますか？</h2><p class="muted">点検済みの項目は重複加算されません。</p><div class="inspection-grid">${INSPECTIONS.map(([id,label,time])=>`<button class="inspect ${state.inspectedItems.has(id)?'checked':''} ${recommended&&state.currentCase.important.includes(id)?'recommended':''}" data-inspect="${id}">${state.inspectedItems.has(id)?'✓ ':''}${label}<br><small>想定 ${time}秒</small></button>`).join('')}</div></section><aside class="panel result-log"><h2>点検記録</h2>${state.inspectionHistory.length?state.inspectionHistory.map(x=>`<div class="log-item"><b>${esc(x.label)}</b><p class="muted">${esc(x.result)}</p></div>`).join(''):'<p class="muted">まだ点検していません。</p>'}</aside></div><div class="screen-actions"><button class="btn ghost" data-action="monitor">監視画面へ</button><button class="btn" data-action="cause">原因を判断する →</button></div>`,true);}
function doInspect(id){if(state.inspectedItems.has(id)){notify('この箇所は点検済みです。時間と減点は加算されません。');return;}const item=INSPECTIONS.find(x=>x[0]===id);state.inspectedItems.add(id);state.simulatedWorkTime+=item[2];const result=state.currentCase.findings[id]||'異常なし。この箇所には、現在の警報につながる明確な異常は確認できません。';state.inspectionHistory.unshift({id,label:item[1],result});showModal(`<div class="eyebrow">INSPECTION RESULT</div><h2 id="modal-title">${esc(item[1])}</h2><p class="feedback">点検結果：${esc(result)}</p><button class="btn" data-action="close-modal">記録して閉じる</button>`);inspect();}
function cause(){state.currentStep=3;setScreen(`${gameHeader()}<section class="panel"><div class="eyebrow">DIAGNOSIS</div><h2>点検結果を説明できる原因は？</h2><p class="muted">運転データと点検記録を比較し、最も妥当な原因を選択してください。</p>${state.feedback?`<div class="feedback">${esc(state.feedback)}</div>`:''}<div class="options">${state.currentCase.causes.map(x=>`<button class="option" data-cause="${esc(x)}">${esc(x)}</button>`).join('')}</div></section><div class="screen-actions"><button class="btn ghost" data-action="inspect">点検へ戻る</button></div>`,true);}
function chooseCause(value){state.selectedCause=value;if(value!==state.currentCase.cause){state.causeMistakes++;state.simulatedWorkTime+=60;state.feedback='選択した原因では、確認済みの点検結果をすべて説明できません。運転データと点検結果をもう一度比較してください。';cause();return;}state.feedback='';safety();}
function safety(){state.currentStep=4;setScreen(`${gameHeader()}<section class="panel"><div class="eyebrow">SAFETY ISOLATION</div><h2>安全措置を順番に実施</h2><p class="muted">必要な措置を作業順に選択してください。選択順は番号で表示されます。順序を誤った場合は選択をやり直せます。</p>${state.feedback?`<div class="feedback">${esc(state.feedback)}</div>`:''}<div class="options">${Object.entries(SAFE_LABELS).map(([id,label])=>{const n=state.completedSafetySteps.indexOf(id);return `<button class="option safety-btn ${n>=0?'selected':''}" data-safe="${id}"><span class="safety-num">${n>=0?n+1:'·'}</span>${label}</button>`}).join('')}</div></section><div class="screen-actions"><button class="btn ghost" data-action="reset-safety" ${state.completedSafetySteps.length?'':'disabled'}>選択をやり直す</button><button class="btn" data-action="action">安全を確認し、処置へ →</button></div>`,true);}
function chooseSafe(id){if(state.completedSafetySteps.includes(id))return;state.completedSafetySteps.push(id);state.simulatedWorkTime+=15;safety();}
function resetSafety(){state.completedSafetySteps=[];state.feedback='安全措置の選択をリセットしました。作業順に選び直してください。';safety();}
function actionScreen(){const required=state.currentCase.safe;const missing=required.filter(x=>!state.completedSafetySteps.includes(x));const chosenOrder=state.completedSafetySteps.filter(x=>required.includes(x));const correctOrder=required.every((x,i)=>chosenOrder[i]===x);if(missing.length||!correctOrder){state.unsafeActionCount++;state.simulatedWorkTime+=60;state.feedback='危険：対象機器はまだ安全に隔離されていないか、安全措置の順序が適切ではありません。報告、待機機確認、負荷移行、停止、エネルギー源遮断の順序を確認してください。';safety();return;}state.feedback='';state.currentStep=5;setScreen(`${gameHeader()}<section class="panel"><div class="eyebrow">CORRECTIVE ACTION</div><h2>適切な処置を選択</h2><div class="options">${shuffle([state.currentCase.action,...state.currentCase.wrongActions]).map(x=>`<button class="option" data-treatment="${esc(x)}">${esc(x)}</button>`).join('')}</div></section>`,true);}
function chooseAction(value){state.selectedAction=value;if(value!==state.currentCase.action){state.actionMistakes++;state.simulatedWorkTime+=120;state.feedback='この処置は確認済みの原因を解消しません。不要な分解や状態悪化につながる可能性があります。';showModal(`<div class="eyebrow">ACTION REVIEW</div><h2 id="modal-title">処置を再検討</h2><p class="feedback">${esc(state.feedback)}</p><button class="btn" data-action="close-modal">戻る</button>`);return;}state.simulatedWorkTime+=300;repair();}
function repair(){state.repairing=true;setScreen(`${gameHeader()}<section class="panel center"><div class="eyebrow">MAINTENANCE IN PROGRESS</div><h2>${esc(state.currentCase.repair)}</h2><div class="progress"><span id="repair-progress"></span></div><p class="muted" id="repair-text">安全状態を再確認しています…</p><button class="btn" id="trial-next" data-action="trial" disabled>試運転へ進む</button></section>`,true);requestAnimationFrame(()=>{document.querySelector('#repair-progress').style.width='100%';setTimeout(()=>{const b=document.querySelector('#trial-next');if(b){b.disabled=false;document.querySelector('#repair-text').textContent='処置完了。復旧確認へ進めます。';}},1500);});}
function trial(){state.currentStep=6;state.trialIndex=0;setScreen(`${gameHeader()}<section class="panel center"><div class="eyebrow">RESTORATION TEST</div><h2>試運転・復旧確認</h2><div class="flow">${['復旧確認','安全措置解除','始動準備','発電機始動','無負荷確認','並列投入','負荷上昇','データ確認'].map((x,i)=>`${i?'<span class="flow-arrow">›</span>':''}<div class="flow-step">${x}</div>`).join('')}</div><p class="muted">処置後の機器を段階的に復旧し、値が正常範囲で安定することを確認します。</p><div class="test-value"><small>${esc(state.currentCase.trial.label)}</small><br><strong id="trial-value">${esc(state.currentCase.trial.values[0])}</strong></div><div id="normal-result"></div><button class="btn large" id="trial-start" data-action="run-trial">試運転開始</button></section>`,true);}
function runTrial(){const btn=document.querySelector('#trial-start');if(!btn||btn.disabled)return;btn.disabled=true;let i=0;const values=state.currentCase.trial.values,el=document.querySelector('#trial-value');const interval=setInterval(()=>{i++;if(i<values.length){el.textContent=values[i];state.simulatedWorkTime+=60;}if(i===values.length-1){clearInterval(interval);state.isRecovered=true;document.querySelector('#normal-result').innerHTML='<div class="normal-banner">GENERATOR NORMAL<br><small>復旧確認完了</small></div>';btn.textContent='結果を見る →';btn.disabled=false;btn.dataset.action='result';}},700);}
function scoreResult(){const unnecessary=[...state.inspectedItems].filter(x=>!state.currentCase.important.includes(x)).length;const mult=state.difficulty==='advanced'?1.5:state.difficulty==='beginner'?.75:1;let score=1000+200+200+200-Math.round(unnecessary*50*mult)-state.causeMistakes*100-Math.round(state.actionMistakes*150*mult)-state.unsafeActionCount*300-(state.hintCount+state.aiAssistCount)*80-Math.floor(state.simulatedWorkTime/300)*20;return Math.max(0,score);}
function result(){stopTimer();state.elapsedTime=Math.floor((Date.now()-state.startTime)/1000);state.score=scoreResult();const unnecessary=[...state.inspectedItems].filter(x=>!state.currentCase.important.includes(x)).length;const rank=state.score>=1300?'CHIEF ENGINEER':state.score>=1100?'SECOND ENGINEER':state.score>=900?'THIRD ENGINEER':state.score>=700?'JUNIOR ENGINEER':'TRAINEE';setScreen(`<section class="center"><div class="eyebrow">MISSION COMPLETE</div><h1>復旧完了</h1><div class="score">${state.score}</div><h2 class="rank">${rank}</h2></section><div class="grid cols-2"><section class="panel"><h2>ミッション記録</h2>${[['発生したトラブル',state.currentCase.title],['原因',state.currentCase.cause],['正しい処置',state.currentCase.action],['実経過時間',formatTime(state.elapsedTime)],['作業想定時間',formatTime(state.simulatedWorkTime)],['点検回数',state.inspectedItems.size],['必要点検数',state.currentCase.important.length],['不要点検数',unnecessary],['原因判断の誤り',state.causeMistakes],['処置選択の誤り',state.actionMistakes],['危険操作',state.unsafeActionCount],['ヒント使用',state.hintCount],['AI相談',state.aiAssistCount]].map(([a,b])=>`<div class="stat"><span>${a}</span><b>${esc(b)}</b></div>`).join('')}</section><section class="panel"><h2>デブリーフィング</h2><h3 class="state-normal">良かった判断</h3><p class="muted">原因を特定し、安全を確認して正常復旧まで完了しました。</p><h3 class="state-warning">改善すべき判断</h3><p class="muted">${unnecessary?'不要な点検を減らし、警報とデータから優先順位を付けましょう。':'点検対象を効率よく絞り込めています。'}${state.unsafeActionCount?' 隔離完了前に処置へ進まないことが重要です。':''}</p><h3>推奨される点検順序</h3><p class="muted">${state.currentCase.important.map(id=>INSPECTIONS.find(x=>x[0]===id)[1]).join(' → ')}</p><h3>今回の学習ポイント</h3><p class="muted">${state.currentCase.learning}</p></section></div><div class="screen-actions"><button class="btn ghost" data-action="retry">同じケースに再挑戦</button><button class="btn" data-action="another">別のトラブルに挑戦</button><button class="btn ghost" data-action="guide">遊び方を見る</button><button class="btn ghost" data-action="title">タイトルへ戻る</button></div>`);}
function showHint(){if(!state.currentCase)return;const max=state.difficulty==='advanced'?0:3;if(max===0){notify('上級ではヒントを使用できません。');return;}const idx=Math.min(state.hintCount,state.currentCase.hints.length-1);state.hintCount++;showModal(`<div class="eyebrow">HINT ${Math.min(state.hintCount,3)} / 3</div><h2 id="modal-title">診断ヒント</h2><p class="feedback">${esc(state.currentCase.hints[idx])}</p><p class="muted">ヒント使用としてスコアから80点減点されます。</p>`);}
function aiPrompt(){const checks=state.inspectionHistory.length?state.inspectionHistory.map(x=>`・${x.label}：${x.result}`).join('\n'):'・まだ点検していません';return `船舶用ディーゼル発電機で、以下の異常が発生しています。\n\n【警報】\n${state.currentCase.alarm}\n\n【運転データ】\n${state.currentCase.data.map(x=>`・${x[0]}：${x[1]}`).join('\n')}\n\n【実施済みの点検】\n${checks}\n\n考えられる原因と、次に優先して確認すべき点検箇所を説明してください。\n原因を断定せず、安全上の注意と点検の優先順位を示してください。`;}
function showAi(){if(!state.currentCase)return;state.aiAssistCount++;showModal(`<div class="eyebrow">AI CONSULTATION PROMPT</div><h2 id="modal-title">AI相談用プロンプト</h2><pre class="prompt" id="ai-prompt">${esc(aiPrompt())}</pre><button class="btn" data-action="copy">プロンプトをコピー</button><p class="muted">実際のAI APIには接続しません。使用1回につき80点減点されます。</p>`);}
function guide(){showModal(`<div class="eyebrow">HOW TO PLAY</div><h2 id="modal-title">遊び方</h2><p class="muted">警報と運転データを比較し、必要な箇所を点検します。点検結果から原因を選び、安全措置を順番に実施してから適切な処置を選択してください。最後に試運転で正常復旧を確認します。</p><div class="flow">${STEPS.map((x,i)=>`${i?'<span class="flow-arrow">›</span>':''}<div class="flow-step">${i+1}. ${x}</div>`).join('')}</div><div class="notice">教育用シミュレーションです。実機では正式な手順書・SMS・責任者の指示に従ってください。</div>`);}
function showModal(html){modalContent.innerHTML=html;modal.hidden=false;document.body.style.overflow='hidden';setTimeout(()=>modal.querySelector('.modal-close').focus(),0);}
function closeModal(){modal.hidden=true;document.body.style.overflow='';}
function notify(msg){toast.textContent=msg;toast.classList.add('show');setTimeout(()=>toast.classList.remove('show'),3000);}
function shuffle(a){return [...a].sort(()=>Math.random()-.5);}

document.addEventListener('click',async e=>{const inspectBtn=e.target.closest('[data-inspect]');if(inspectBtn){doInspect(inspectBtn.dataset.inspect);return;}const causeBtn=e.target.closest('[data-cause]');if(causeBtn){chooseCause(causeBtn.dataset.cause);return;}const safeBtn=e.target.closest('[data-safe]');if(safeBtn){chooseSafe(safeBtn.dataset.safe);return;}const treat=e.target.closest('[data-treatment]');if(treat){chooseAction(treat.dataset.treatment);return;}const b=e.target.closest('[data-action]');if(!b)return;e.preventDefault();const a=b.dataset.action;if(a==='title')intro();else if(a==='guide')guide();else if(a==='setup')setup();else if(a==='start')start();else if(a==='monitor')monitor();else if(a==='inspect')inspect();else if(a==='cause')cause();else if(a==='action')actionScreen();else if(a==='trial')trial();else if(a==='run-trial')runTrial();else if(a==='result')result();else if(a==='hint')showHint();else if(a==='ai')showAi();else if(a==='close-modal')closeModal();else if(a==='retry')start(state.currentCase.id);else if(a==='another'){setup();}else if(a==='copy'){try{await navigator.clipboard.writeText(document.querySelector('#ai-prompt').textContent);notify('相談用プロンプトをコピーしました。ChatGPTやCopilotに貼り付けて使用できます。');}catch{notify('コピーできませんでした。テキストを選択してコピーしてください。');}}});
document.addEventListener('click',e=>{if(e.target.closest('[data-action="reset-safety"]'))resetSafety();});
document.addEventListener('keydown',e=>{if(e.key==='Escape'&&!modal.hidden)closeModal();});
intro();
